---
base: &base
  adapter:  postgresql
  username: waterfall
  password: blueh20
  host:     localhost

development: 
  <<: *base
  database: oauth_dev

production:
  <<: *base
  database: oauth_production

test: &test
  <<: *base
  database: oauth_test